FROM python:3.11-slim

ARG SERVICE_NAME

ENV SERVICE_NAME=${SERVICE_NAME}
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./${SERVICE_NAME}/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

CMD sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"