version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgreSQL:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
    env_file:
      - .env
    volumes:
      - ReserveMSA_psql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --notify-keyspace-events KEA
    ports:
      - "6379:6379"
    volumes:
      - ReserveMSA_redis:/data

  user_service:
    build:
      context: .
      dockerfile: ./Dockerfile.python
      args:
        SERVICE_NAME: user_service
    env_file:
      - .env
    volumes:
      - ./user_service/app:/app
    depends_on:
      - postgreSQL
      - kafka

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user_service

  jaeger:
    image: jaegertracing/all-in-one:latest
    
    ports:
      - "16686:16686"
      - "6831:6831/udp"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - JAEGER_UI_BASE_PATH=/jaeger

volumes:
  ReserveMSA_psql:
  ReserveMSA_redis: